### ISSUE TITLE
Line 21 of STK Push Request

### ISSUE THREAD

**Issue by daviek19** [scedar/m-pesa_going_live#1]
Hey, this doc has helped me a lot. 
kindly assist. When sending an amount greater than 0 but less than 70000 trx goes though with success. How did you land to **Error   message "Bad Request - Invalid Amount"**

**Comment by ochomoswill** [comment]
Glad to have helped. Sorry, for the extremely delayed response. **Error message "Bad Request - Invalid Amount"** is when the amount is above 70000.
